name = "DistanceAndSimilarity"
uuid = "b91ac959-d9c4-4de6-beb7-dee885e75531"
authors = ["Nicolas Magalhães"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
